# Generated by Django 5.0.3 on 2024-03-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
