# Generated by Django 5.0.3 on 2024-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/big/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium_img',
            field=models.ImageField(blank=True, null=True, upload_to='product/medium', verbose_name='Среднее изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='product/small/', verbose_name='Малое изображение'),
        ),
    ]
